version: "3"

services:
  recorder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: m3u8AutoRecorder
    restart: always
    volumes:
      # Mount a local directory to the /data directory in the container
      - /etc/recorder:/data
    environment:
      # Monitoring interval
      - INTERVAL_SECONDS=60
      # M3U8 URL
      - M3U8_URL=YOUR_M3U8_URL_HERE
      # Timezone (optional)
      - TZ=Asia/Shanghai
